name: Release To Prod

on:
  push:
    tags:
      - '*.*.*'

jobs:
  test:
    if: ${{ startsWith(github.event.base_ref, 'refs/heads/release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          make lint
          make report
      - name: Test
        run: |
          make test-unit
      - name: Send code coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to gcr
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push image
        run: |
          make build-image VERSION=$VERSION GITHUB_TOKEN=${{ secrets.TOKEN }} DEPLOY_TO=prod
          make push-image VERSION=$VERSION
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - test
      - publish
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          sed -i 's/git@github.com:/https:\/\/'"${{ secrets.USERNAME }}"':'"${{ secrets.TOKEN }}"'@github.com\//' .gitmodules
          git submodule update --init --recursive
      - name: Prepare
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm repo add blackhorseya https://blackhorseya.github.io/helm-charts/
      - name: Deploy
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
        run: |
          echo $KUBECONFIG_FILE | base64 --decode > ./kubeconfig.yaml && export KUBECONFIG=./kubeconfig.yaml
          make deploy DEPLOY_TO=prod VERSION=$VERSION
